### ISSUE TITLE
Hi, where get the trained-model

### ISSUE THREAD

**Issue by CountofMont** [liuf1990/3DFC#4]

**Comment by haimingZZ** [comment]
Outstanding results! waiting for pretrained-model && training code as well.

**Comment by kuangcy1998** [comment]
Thanks for the outstanding work! Will you release the pre-trained model recently?

**Comment by liufeng2915** [comment]
Please download the pre-trained model [here](https://drive.google.com/file/d/16yV4sgXvoKnlEpaTpnkJu2eix4q61ONg/view?usp=sharing).
