### ISSUE TITLE
How can I get triangulation after establishing dense correspondence?

### ISSUE THREAD

**Issue by SHITINGCHEN** [liuf1990/3DFC#5]
After sending the raw scan into the network, how can I get the triangulation since the output is only vertex values? Are the output vertices in the same triangulation as the BFM template does? But I don't see template triangulation provided in this repo.

**Comment by shoerley** [comment]
I don't think raw scans are to be injected into the network : they should be preprocessed first. But @SHITINGCHEN, tell me: did you manage to get something from the network without the model ? I would be very interested to know what and how. Thanks for you reply.

**Comment by liufeng2915** [comment]
Please find the triangulation and other information [here](https://drive.google.com/file/d/1zMlB9j6MPJYU4i957E_dM_McF9TR-57Z/view).
